[General]
panels=panel1

[panel1]
plugins=fancymenu,quicklaunch,taskbar,statusnotifier,sysstat,sensors,volume,worldclock,showdesktop
position=Bottom
desktop=0
panelSize=36
iconSize=22
screen-name=HEADLESS-1

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=150

[quicklaunch]
type=quicklaunch
alignment=Left
apps\size=3
apps\1\desktop=/usr/share/applications/steam.desktop
apps\2\desktop=/usr/share/applications/firefox.desktop
apps\3\desktop=/usr/share/applications/qterminal.desktop

[taskbar]
type=taskbar
buttonWidth=220
closeOnMiddleClick=true
groupingEnabled=false

[statusnotifier]
type=statusnotifier
alignment=Right

[sysstat]
type=sysstat
alignment=Right

[sensors]
type=sensors
alignment=Right

[volume]
type=volume
device=0
alignment=Right

[worldclock]
type=worldclock
alignment=Right

[showdesktop]
type=showdesktop
alignment=Right
